version: '3.4'

services:

  collection.db:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - collection-sqldata:/var/opt/mssql

  isearch:
    environment:
      - ConnectionStrings__collectionDbContextConnection=Server=collection.db;Database=MediaCollection;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5292:80"
      - "7140:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

volumes:
  collection-sqldata:
    external: false